# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171025_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default=b' ', max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Team', to='accounts.Team')),
            ],
            options={
                'ordering': ['-date_created'],
                'verbose_name_plural': 'Point Changes ',
            },
        ),
    ]
