# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171024_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Team '},
        ),
        migrations.AddField(
            model_name='comment',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivedby', to='accounts.Team'),
        ),
    ]
